apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeclock-api
spec:
  rules:
    - host: timeclock.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: timeclock-api
                port:
                  number: 80